version: 0.2
phases:
  build:
    commands:
      - echo "building frontend"
      - pwd
      - npm install
      - ng build
      - aws s3 sync "./dist/network-devices-ui" "s3://network-device-frontend/device/"
#      - aws cloudfront create-invalidation --distribution-id "CLOUDFRONT_ID" --paths '/*'
