version: 0.2
phases:
  build:
    commands:
      - echo "building frontend"
      - pwd
      - npm install -g @angular/cli@6.0.0
      - npm install
      - ng build
  post_build:
    commands:
      - aws s3 sync dist/network-devices-ui s3://$BUCKET_NAME --delete
      - aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_ID" --paths '/*'
